// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Country struct {
	ID   pgtype.UUID
	Name string
	Code string
}

type Ingredient struct {
	ID   pgtype.UUID
	Name string
}

type Instruction struct {
	ID              pgtype.UUID
	RecipeID        pgtype.UUID
	StepNumber      int32
	InstructionText string
}

type Recipe struct {
	ID           pgtype.UUID
	Title        string
	Servings     int32
	ServingsType string
	CountryID    pgtype.UUID
	SourceID     pgtype.UUID
	OriginalUrl  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RecipeIngredient struct {
	RecipeID     pgtype.UUID
	IngredientID pgtype.UUID
	Amount       pgtype.Numeric
	Unit         pgtype.Text
}

type Source struct {
	ID   pgtype.UUID
	Name string
	Url  string
}
